const DATA = {
  version: '2.0',
  phases: [
    { id:'az900', title:'Phase 1: AZ-900 bestehen', subtitle:'Microsoft Azure Fundamentals', weeks:'Woche 1–4', modules:[
      {id:'az-cloud-basics', title:'Cloud Computing & Shared Responsibility', time:'AZ-900 · Cloud concepts', tags:['Cloud','Responsibility','Basics'], summary:'Du lernst nicht nur, dass es Cloud gibt, sondern was Cloud Computing bedeutet und wer in welchem Modell verantwortlich ist.', topics:[
        {title:'Cloud Computing', learn:'Cloud Computing bedeutet, IT-Ressourcen über das Internet bereitzustellen: Rechenleistung, Speicher, Netzwerke, Datenbanken, Anwendungen und Analysefunktionen. Der Kern ist: Du musst Hardware nicht selbst kaufen, betreiben und skalieren, sondern nutzt Ressourcen nach Bedarf.', example:'Beispiel: Statt einen eigenen Server zu kaufen, erstellst du in Azure eine virtuelle Maschine oder hostest eine App als Web App.', check:'Kannst du erklären, warum Cloud nicht einfach „Computer von jemand anderem“ ist, sondern ein Betriebs- und Abrechnungsmodell?'},
        {title:'Shared Responsibility Model', learn:'Microsoft und der Kunde teilen sich Verantwortung. Microsoft betreibt die physische Infrastruktur der Azure-Rechenzentren. Je nach Diensttyp bist du aber weiterhin für Daten, Identitäten, Zugriffsrechte, Konfigurationen und teilweise Betriebssysteme verantwortlich.', example:'Bei IaaS verwaltest du z. B. Betriebssystem-Updates einer VM selbst. Bei SaaS wie Microsoft 365 verwaltest du eher Benutzer, Daten und Berechtigungen.', check:'Merke: Je näher am fertigen Produkt, desto mehr übernimmt Microsoft. Je näher an Infrastruktur, desto mehr bleibt bei dir.'},
        {title:'Was Microsoft bei AZ-900 erwartet', learn:'Du musst Begriffe nicht programmieren, sondern erklären und Szenarien zuordnen können. Typische Prüfungslogik: „Wer ist verantwortlich?“, „Welches Modell passt?“, „Welcher Diensttyp ist sinnvoll?“', example:'Frage: Ein Unternehmen will maximale Kontrolle über Betriebssystem und Netzwerk. Antwortlogik: eher IaaS/VM.', check:'Du bist bereit, wenn du Verantwortung in IaaS, PaaS und SaaS vergleichen kannst.'}
      ]},
      {id:'az-cloud-models', title:'Cloud-Modelle, Preislogik & Serverless', time:'AZ-900 · Cloud concepts', tags:['Public','Hybrid','Serverless'], summary:'Du verstehst Public, Private, Hybrid Cloud, nutzungsbasierte Abrechnung, Preismodelle und Serverless.', topics:[
        {title:'Public Cloud', learn:'Public Cloud bedeutet: Cloud-Ressourcen werden von einem Anbieter wie Microsoft betrieben und mehreren Kunden über das Internet bereitgestellt. Kunden teilen sich nicht ihre Daten, aber die zugrunde liegende Plattform ist mandantenfähig.', example:'Ein Startup hostet seine Web-App in Azure, ohne eigene Server zu kaufen.', check:'Use Case: schnell starten, global skalieren, keine eigene Hardware.'},
        {title:'Private Cloud', learn:'Private Cloud ist eine Cloud-ähnliche Umgebung, die exklusiv für eine Organisation betrieben wird. Sie kann im eigenen Rechenzentrum oder durch einen Anbieter betrieben werden. Der Fokus liegt auf Kontrolle und speziellen Anforderungen.', example:'Eine Organisation mit sehr strengen internen Vorschriften betreibt Workloads in einer privaten Umgebung.', check:'Use Case: hohe Kontrolle, spezielle Compliance, eigene Betriebsregeln.'},
        {title:'Hybrid Cloud', learn:'Hybrid Cloud verbindet lokale/private Infrastruktur mit Public Cloud. Sie ist typisch, wenn Unternehmen nicht alles auf einmal migrieren oder bestimmte Daten lokal behalten möchten.', example:'Eine alte Datenbank bleibt lokal, eine neue Web-App läuft in Azure und greift gesichert darauf zu.', check:'Use Case: Migration Schritt für Schritt, lokale Systeme plus Cloud.'},
        {title:'Consumption-based Model', learn:'Bei nutzungsbasierter Abrechnung zahlst du grundsätzlich für Ressourcen, die du verwendest. Das reduziert Vorabinvestitionen, verlangt aber Kostenkontrolle.', example:'Eine VM kostet, solange sie läuft; Storage kostet nach gespeicherter Datenmenge, Redundanz und Zugriffsmuster.', check:'Wichtig: Cloud ist nicht automatisch billiger. Sie wird billiger, wenn Ressourcen passend dimensioniert und überwacht werden.'},
        {title:'Serverless', learn:'Serverless bedeutet nicht, dass keine Server existieren. Es bedeutet, dass du Server nicht selbst verwaltest. Du konzentrierst dich auf Code, Ereignisse und Logik.', example:'Azure Functions führt Code aus, wenn ein Event passiert, z. B. Datei hochgeladen oder HTTP-Anfrage empfangen.', check:'Merke: Serverless = weniger Infrastrukturverwaltung, ereignisgetriebene Ausführung.'}
      ]},
      {id:'az-benefits', title:'Cloud-Vorteile verstehen', time:'AZ-900 · Cloud benefits', tags:['HA','Scale','Governance'], summary:'Du lernst die offiziellen Cloud-Vorteile mit prüfungsnahen Beispielen.', topics:[
        {title:'High Availability', learn:'Hochverfügbarkeit bedeutet, dass ein Dienst auch bei Ausfällen möglichst erreichbar bleibt. In Azure erreicht man das z. B. durch Redundanz, Availability Zones und passende Architektur.', example:'Eine App läuft über mehrere Zonen, damit ein Standortausfall nicht die ganze App stoppt.', check:'Frage dich: Wie bleibt der Dienst verfügbar, wenn eine Komponente ausfällt?'},
        {title:'Scalability und Elasticity', learn:'Skalierbarkeit bedeutet, Ressourcen an Bedarf anzupassen. Vertikal bedeutet stärkere Maschine; horizontal bedeutet mehr Instanzen. Elastizität bedeutet automatisches Hoch- und Runterskalieren.', example:'Ein Onlineshop skaliert vor Weihnachten automatisch mehr Instanzen hoch.', check:'Horizontal = mehr Einheiten. Vertikal = größere Einheit.'},
        {title:'Reliability und Predictability', learn:'Reliability beschreibt die Fähigkeit, Fehler zu überstehen und sich zu erholen. Predictability bedeutet vorhersehbares Verhalten bei Leistung und Kosten, wenn Ressourcen sauber geplant sind.', example:'Mit Azure Monitor, Advisor und Budgets erkennst du Probleme und Kostenentwicklung früh.', check:'Reliability ist Ausfallsicherheit; Predictability ist Planbarkeit.'},
        {title:'Security und Governance', learn:'Cloud bietet integrierte Sicherheits- und Governance-Werkzeuge: Identität, Zugriff, Richtlinien, Überwachung, Compliance-Tools und Sicherheitsbewertungen.', example:'Azure Policy erzwingt, dass Ressourcen nur in erlaubten Regionen erstellt werden.', check:'Security schützt; Governance stellt Regeln und Kontrolle sicher.'},
        {title:'Manageability', learn:'Manageability bedeutet, Ressourcen zentral verwalten zu können: Portal, CLI, PowerShell, APIs, Templates, Monitoring und Automatisierung.', example:'Du erstellst Ressourcen im Portal oder automatisiert mit ARM Templates.', check:'Prüfungslogik: Welches Tool hilft bei Verwaltung, Deployment oder Überwachung?'}
      ]},
      {id:'az-service-types', title:'IaaS, PaaS, SaaS sicher unterscheiden', time:'AZ-900 · Service types', tags:['IaaS','PaaS','SaaS'], summary:'Dieser Bereich ist prüfungsrelevant, weil viele Szenariofragen über Service-Modelle laufen.', topics:[
        {title:'IaaS', learn:'Infrastructure as a Service stellt grundlegende Infrastruktur bereit: virtuelle Maschinen, Netzwerke und Speicher. Du hast viel Kontrolle, aber auch mehr Verantwortung.', example:'Du betreibst eine Windows- oder Linux-VM und verwaltest Betriebssystem, Updates und installierte Software.', check:'IaaS passt, wenn du Betriebssystemkontrolle brauchst.'},
        {title:'PaaS', learn:'Platform as a Service stellt eine Plattform für Anwendungen bereit. Du verwaltest nicht die darunterliegenden Server, sondern konzentrierst dich auf App, Code und Konfiguration.', example:'Azure App Service hostet eine Web-App, ohne dass du selbst den Webserver administrierst.', check:'PaaS passt, wenn du App bereitstellen willst, ohne Serverbetrieb.'},
        {title:'SaaS', learn:'Software as a Service ist fertige Software über das Internet. Du verwaltest Nutzer, Daten und Einstellungen, aber nicht Anwendungscode oder Infrastruktur.', example:'Microsoft 365, Dynamics 365 oder andere fertige Cloud-Anwendungen.', check:'SaaS passt, wenn du fertige Software nutzen willst.'},
        {title:'Prüfungslogik', learn:'Microsoft fragt oft indirekt: Wer verwaltet was? Wie viel Kontrolle braucht ein Unternehmen? Wie schnell soll ein Dienst ohne Infrastrukturaufwand bereitstehen?', example:'„Das Unternehmen will keine Server patchen und nur Code deployen“ → PaaS oder Serverless, nicht IaaS.', check:'Trainiere die Zuordnung über Verantwortung und Kontrolle.'}
      ]},
      {id:'az-architecture-core', title:'Azure-Architektur: Regionen, Zonen, Hierarchie', time:'AZ-900 · Architecture', tags:['Regions','Zones','Hierarchy'], summary:'Du verstehst die räumliche und organisatorische Struktur von Azure.', topics:[
        {title:'Azure Regions', learn:'Eine Azure Region ist ein geografischer Bereich mit mindestens einem oder mehreren Rechenzentren. Ressourcen werden in Regionen erstellt, damit Latenz, Datenresidenz und Verfügbarkeit geplant werden können.', example:'Eine deutsche Organisation kann Ressourcen in einer europäischen Region bereitstellen, um Nähe und regulatorische Anforderungen zu berücksichtigen.', check:'Region = geografischer Azure-Standort.'},
        {title:'Availability Zones', learn:'Availability Zones sind physisch getrennte Standorte innerhalb einer Region. Sie haben eigene Stromversorgung, Kühlung und Netzwerk. Sie erhöhen Ausfallsicherheit innerhalb einer Region.', example:'Eine Datenbank oder App wird zone-redundant bereitgestellt, damit ein Zonenausfall abgefangen wird.', check:'Zone = getrennte Ausfallgrenze innerhalb einer Region.'},
        {title:'Region Pairs', learn:'Region Pairs sind gekoppelte Azure-Regionen, die für Resilienz, geplante Wartung und Disaster-Recovery-Strategien relevant sind.', example:'Bei großem Ausfall kann eine zweite Region Teil der Wiederherstellungsstrategie sein.', check:'Region Pair = regionale Resilienzplanung.'},
        {title:'Sovereign Regions', learn:'Sovereign Regions sind spezielle Cloud-Regionen für besondere rechtliche, staatliche oder regulatorische Anforderungen.', example:'Regierungen oder stark regulierte Organisationen können spezielle souveräne Cloud-Angebote benötigen.', check:'Sovereign = besondere rechtliche/hoheitliche Anforderungen.'},
        {title:'Azure-Hierarchie', learn:'Die Grundhierarchie lautet: Management Group → Subscription → Resource Group → Resource. Management Groups organisieren mehrere Subscriptions. Subscriptions sind Verwaltungs- und Abrechnungsgrenzen. Resource Groups gruppieren Ressourcen.', example:'Ein Unternehmen trennt Produktion und Test über Subscriptions und gruppiert Ressourcen einer App in einer Resource Group.', check:'Diese Reihenfolge musst du auswendig können.'}
      ]},
      {id:'az-compute-hosting', title:'Compute & App Hosting', time:'AZ-900 · Services', tags:['VM','Containers','Functions'], summary:'Du lernst die wichtigsten Compute-Optionen und wann sie eingesetzt werden.', topics:[
        {title:'Virtual Machines', learn:'Azure Virtual Machines sind virtuelle Server. Sie bieten viel Kontrolle über Betriebssystem, Software und Konfiguration. Dafür bist du stärker für Wartung, Updates und Sicherheit verantwortlich.', example:'Eine Legacy-Anwendung braucht Windows Server und spezielle installierte Software.', check:'VM = maximale Kontrolle, mehr Verwaltungsaufwand.'},
        {title:'VM Scale Sets', learn:'Virtual Machine Scale Sets verwalten mehrere identische VM-Instanzen und können sie skalieren. Sie sind für Lastverteilung und skalierbare VM-Workloads gedacht.', example:'Eine Webanwendung läuft auf mehreren identischen VM-Instanzen und skaliert bei Last.', check:'Scale Set = viele ähnliche VMs automatisch verwalten.'},
        {title:'Availability Sets', learn:'Availability Sets verteilen VMs über Fehler- und Updatedomänen, um Ausfälle durch Hardwareprobleme oder Wartung zu reduzieren.', example:'Zwei VMs derselben App liegen in unterschiedlichen Fault Domains.', check:'Availability Set = Verfügbarkeit für VMs innerhalb eines Rechenzentrumskonzepts.'},
        {title:'Azure Virtual Desktop', learn:'Azure Virtual Desktop stellt virtuelle Desktops und Anwendungen aus der Cloud bereit.', example:'Mitarbeiter greifen remote auf einen Windows-Desktop oder Unternehmensapps zu.', check:'Virtual Desktop = Desktop-/App-Virtualisierung für Nutzer.'},
        {title:'Containers', learn:'Container paketieren Anwendung und Abhängigkeiten. Sie sind leichter als VMs und eignen sich für portable, schnell startende Anwendungen.', example:'Eine App läuft als Docker-Container lokal, in Tests und später in Azure.', check:'Container = portable App-Umgebung, weniger schwergewichtig als VM.'},
        {title:'Azure Functions', learn:'Azure Functions ist serverless Compute. Code läuft ereignisgesteuert, z. B. bei HTTP-Anfragen, Timer, Queue-Nachrichten oder Datei-Uploads.', example:'Wenn eine Datei in Storage landet, verarbeitet eine Function sie automatisch.', check:'Function = kleine Event-getriebene Codeeinheit.'},
        {title:'Application Hosting Options', learn:'Für Apps kommen Web Apps, Container oder VMs infrage. Web Apps sind PaaS und einfach zu betreiben. Container bieten Portabilität. VMs bieten maximale Kontrolle.', example:'Neue Web-App ohne Serverbetrieb → Web App. Legacy-App mit OS-Abhängigkeiten → VM.', check:'Wähle nach Kontrolle, Betriebsaufwand und Portabilität.'}
      ]},
      {id:'az-networking', title:'Azure Networking', time:'AZ-900 · Services', tags:['VNet','VPN','Endpoints'], summary:'Du verstehst virtuelle Netzwerke, Verbindungen, DNS und öffentliche/private Endpunkte.', topics:[
        {title:'Azure Virtual Network', learn:'Ein Azure Virtual Network ist dein privates Netzwerk in Azure. Ressourcen wie VMs können darin miteinander kommunizieren.', example:'Eine Web-VM und eine Datenbank-VM liegen im selben VNet oder in verbundenen VNets.', check:'VNet = privater Netzwerkbereich in Azure.'},
        {title:'Subnets', learn:'Subnets teilen ein VNet in kleinere Netzwerkbereiche. Damit kannst du Ressourcen logisch trennen und Sicherheitsregeln gezielter anwenden.', example:'Webserver im Frontend-Subnet, Datenbank im Backend-Subnet.', check:'Subnet = Unterteilung eines VNets.'},
        {title:'Peering', learn:'VNet Peering verbindet zwei virtuelle Netzwerke, damit Ressourcen privat miteinander kommunizieren können.', example:'Ein Hub-VNet ist mit mehreren Spoke-VNets verbunden.', check:'Peering = private Verbindung zwischen VNets.'},
        {title:'Azure DNS', learn:'Azure DNS hostet DNS-Zonen und löst Namen in IP-Adressen auf. Es hilft, Dienste über Namen statt IPs erreichbar zu machen.', example:'app.example.com zeigt auf eine Azure-Ressource.', check:'DNS = Namensauflösung.'},
        {title:'VPN Gateway', learn:'Azure VPN Gateway verbindet lokale Netzwerke mit Azure über verschlüsselte Verbindung über das Internet.', example:'Das Firmenbüro verbindet sich per Site-to-Site VPN mit einem Azure VNet.', check:'VPN Gateway = verschlüsselt über öffentliches Internet.'},
        {title:'ExpressRoute', learn:'ExpressRoute stellt eine private Verbindung zwischen lokaler Infrastruktur und Azure bereit, nicht über das öffentliche Internet.', example:'Ein Unternehmen braucht planbare, private Verbindung mit hoher Bandbreite.', check:'ExpressRoute = private Verbindung, nicht Internet-VPN.'},
        {title:'Public vs. Private Endpoints', learn:'Ein Public Endpoint ist öffentlich erreichbar. Ein Private Endpoint macht einen Azure-Dienst über eine private IP im VNet erreichbar.', example:'Storage Account nur privat aus Unternehmensnetz erreichbar machen → Private Endpoint.', check:'Public = öffentlich erreichbar; Private = privater Netzwerkzugriff.'}
      ]},
      {id:'az-storage', title:'Azure Storage & Migration', time:'AZ-900 · Services', tags:['Blob','Files','Redundancy'], summary:'Du lernst Storage-Arten, Redundanz, Zugriffstiers und Werkzeuge zum Verschieben von Daten.', topics:[
        {title:'Blob Storage', learn:'Blob Storage speichert unstrukturierte Daten wie Bilder, Videos, Backups, Logs oder Dokumente. Blob steht für Binary Large Object.', example:'Eine App speichert hochgeladene PDF-Dateien oder Bilder in Blob Storage.', check:'Blob = Objektspeicher für unstrukturierte Daten.'},
        {title:'Azure Files', learn:'Azure Files stellt Dateifreigaben bereit, die über SMB/NFS genutzt werden können. Es ähnelt klassischen File Shares.', example:'Mehrere VMs greifen auf dieselbe Dateifreigabe zu.', check:'Files = verwaltete Dateifreigabe.'},
        {title:'Queue Storage', learn:'Queue Storage speichert Nachrichten, damit Komponenten asynchron miteinander arbeiten können.', example:'Eine Web-App legt eine Nachricht in eine Queue, eine Function verarbeitet sie später.', check:'Queue = Nachrichten entkoppeln Systeme.'},
        {title:'Table Storage', learn:'Table Storage ist ein NoSQL-Key-Value/Tabellenspeicher für strukturierte, nicht relationale Daten.', example:'Speichern einfacher Metadaten mit PartitionKey und RowKey.', check:'Table = einfacher NoSQL-Speicher.'},
        {title:'Storage Tiers', learn:'Storage Tiers steuern Kosten und Zugriff: häufig genutzte Daten sind teurer im Speicher, günstiger im Zugriff; selten genutzte Daten günstiger im Speicher, ggf. teurer/langsamer beim Abruf.', example:'Archivierte Backups gehören eher in kältere Tiers als täglich genutzte App-Dateien.', check:'Tier nach Zugriffshäufigkeit wählen.'},
        {title:'Redundancy Options', learn:'Redundanzoptionen bestimmen, wie Daten kopiert werden. Lokal, zonenübergreifend oder regional/geografisch redundant. Ziel ist Schutz vor Hardware-, Zonen- oder Regionsausfällen.', example:'Geschäftskritische Daten benötigen höhere Redundanz als temporäre Logs.', check:'Mehr Redundanz = mehr Schutz, meist höhere Kosten.'},
        {title:'Storage Tools', learn:'AzCopy ist ein Kommandozeilentool für Datenkopien. Azure Storage Explorer ist eine grafische Oberfläche. Azure File Sync synchronisiert lokale Dateiserver mit Azure Files.', example:'Viele Dateien per Skript hochladen → AzCopy. Manuell ansehen/verwalten → Storage Explorer.', check:'Tool nach Aufgabe unterscheiden.'},
        {title:'Migration Options', learn:'Azure Migrate hilft bei Bewertung und Migration von Servern/Workloads. Azure Data Box ist ein physisches Gerät für große Datenmengen, wenn Upload über Netzwerk unpraktisch ist.', example:'Petabytes an Daten hochladen → Data Box statt Internetupload.', check:'Azure Migrate = Workloads migrieren; Data Box = große Datenmengen transportieren.'}
      ]},
      {id:'az-identity-security', title:'Identität, Zugriff & Security', time:'AZ-900 · Services', tags:['Entra','RBAC','Zero Trust'], summary:'Du lernst die zentralen Sicherheits- und Identitätskonzepte in Azure.', topics:[
        {title:'Microsoft Entra ID', learn:'Microsoft Entra ID ist der cloudbasierte Identitäts- und Zugriffsverwaltungsdienst. Er verwaltet Benutzer, Gruppen, Anwendungen und Authentifizierung.', example:'Mitarbeiter melden sich mit ihrem Organisationskonto an Azure und Microsoft 365 an.', check:'Entra ID = Identität und Anmeldung in der Cloud.'},
        {title:'Microsoft Entra Domain Services', learn:'Entra Domain Services stellt verwaltete Domänendienste wie Domain Join, Gruppenrichtlinien und LDAP/Kerberos/NTLM-Kompatibilität bereit, ohne eigene Domain Controller zu betreiben.', example:'Eine Legacy-App braucht Domain Join, aber du willst keine Domain Controller patchen.', check:'Domain Services = verwaltete klassische Domänenfunktionen.'},
        {title:'SSO, MFA, Passwordless', learn:'Single Sign-On erlaubt eine Anmeldung für mehrere Dienste. MFA verlangt zusätzliche Faktoren. Passwordless ersetzt klassische Passwörter durch sicherere Methoden wie Authenticator, FIDO2 oder biometrische Verfahren.', example:'User meldet sich einmal an und nutzt mehrere Unternehmensapps; bei Risiko wird MFA verlangt.', check:'SSO = bequem; MFA/Passwordless = sicherer.'},
        {title:'External Identities', learn:'External Identities ermöglichen Zugriff für externe Benutzer wie Partner, Kunden oder Gäste.', example:'Ein externer Berater erhält Zugriff auf eine Anwendung, ohne interner Mitarbeiter zu sein.', check:'Extern = Gäste/Partner/Kunden sicher einbinden.'},
        {title:'Conditional Access', learn:'Conditional Access trifft Zugriffsentscheidungen anhand von Signalen: Benutzer, Standort, Gerät, Risiko, Anwendung. Dann kann Zugriff erlaubt, blockiert oder MFA verlangt werden.', example:'Anmeldung aus unbekanntem Land → MFA erforderlich.', check:'Wenn-dann-Regeln für Zugriff.'},
        {title:'RBAC', learn:'Azure Role-Based Access Control weist Rollen auf bestimmten Scopes zu. Rollen definieren, welche Aktionen erlaubt sind; Scopes können Management Group, Subscription, Resource Group oder Resource sein.', example:'Ein Nutzer bekommt „Reader“ auf einer Resource Group und kann Ressourcen sehen, aber nicht ändern.', check:'RBAC = wer darf was auf welchem Bereich?'},
        {title:'Zero Trust', learn:'Zero Trust bedeutet: niemals automatisch vertrauen, immer überprüfen. Identität, Gerät, Standort, Risiko und minimale Rechte sind zentral.', example:'Auch interne Nutzer müssen authentifiziert, autorisiert und überwacht werden.', check:'Prinzip: verify explicitly, least privilege, assume breach.'},
        {title:'Defense in Depth', learn:'Defense in Depth ist Sicherheit in mehreren Schichten: physisch, Identität, Netzwerk, Anwendung, Daten usw. Wenn eine Schicht versagt, schützen weitere Schichten.', example:'MFA, RBAC, Firewalls, Verschlüsselung und Monitoring gemeinsam.', check:'Mehrere Schutzschichten statt eine einzelne Barriere.'},
        {title:'Microsoft Defender for Cloud', learn:'Defender for Cloud hilft, Sicherheitsstatus zu bewerten, Empfehlungen zu geben und Workloads zu schützen.', example:'Defender empfiehlt, offene Ports zu schließen oder Sicherheitskonfigurationen zu verbessern.', check:'Defender for Cloud = Security posture + Schutzempfehlungen.'}
      ]},
      {id:'az-costs', title:'Kostenmanagement in Azure', time:'AZ-900 · Management', tags:['Pricing','Budgets','Tags'], summary:'Du verstehst, wodurch Azure-Kosten entstehen und wie man sie plant/überwacht.', topics:[
        {title:'Kostenfaktoren', learn:'Kosten hängen ab von Diensttyp, Region, Laufzeit, Größe, Speicher, Redundanz, Netzwerkverkehr, Lizenzierung und Support. Nicht jeder Dienst rechnet gleich ab.', example:'Eine größere VM in einer teureren Region mit Premium Storage kostet mehr als eine kleine VM mit Standard Storage.', check:'Kosten = Nutzung × Dienstmodell × Konfiguration.'},
        {title:'Pricing Calculator', learn:'Der Azure Pricing Calculator dient dazu, geplante Ressourcen vorab zu kalkulieren.', example:'Du planst eine Web-App mit Datenbank und schätzt monatliche Kosten.', check:'Vorher schätzen → Pricing Calculator.'},
        {title:'Cost Management', learn:'Azure Cost Management hilft, tatsächliche Kosten zu analysieren, Budgets zu setzen, Ausgaben zu überwachen und Kostentreiber zu erkennen.', example:'Budgetwarnung, wenn 80 % des Monatsbudgets erreicht sind.', check:'Nachher/fortlaufend überwachen → Cost Management.'},
        {title:'Tags', learn:'Tags sind Name-Wert-Paare zur Organisation von Ressourcen. Sie helfen bei Kostenstellen, Projekten, Umgebungen und Verantwortlichkeiten.', example:'Tag CostCenter=Marketing oder Environment=Production.', check:'Tags organisieren und unterstützen Kostenanalyse.'}
      ]},
      {id:'az-governance-tools', title:'Governance, Compliance & Schutz vor Fehlern', time:'AZ-900 · Management', tags:['Policy','Purview','Locks'], summary:'Du lernst Richtlinien, Daten-Governance und Ressourcenschutz kennen.', topics:[
        {title:'Microsoft Purview', learn:'Microsoft Purview unterstützt Daten-Governance, Compliance, Klassifizierung und Verwaltung von Datenlandschaften.', example:'Organisationen erkennen, klassifizieren und verwalten sensible Daten.', check:'Purview = Daten-Governance und Compliance.'},
        {title:'Azure Policy', learn:'Azure Policy erstellt und erzwingt Regeln für Ressourcen. Sie kann Nichtkonformität erkennen oder bestimmte Konfigurationen verhindern.', example:'Nur bestimmte Regionen erlauben oder bestimmte Tags verlangen.', check:'Policy = Regeln für Ressourcen.'},
        {title:'Resource Locks', learn:'Resource Locks schützen Ressourcen vor versehentlichem Löschen oder Ändern. Es gibt Sperren wie CanNotDelete und ReadOnly.', example:'Eine produktive Datenbank erhält eine Löschsperre.', check:'Lock = versehentliche Änderung/Löschung verhindern.'}
      ]},
      {id:'az-deploy-monitor', title:'Verwaltung, Deployment & Monitoring', time:'AZ-900 · Management', tags:['Portal','ARM','Monitor'], summary:'Du verstehst, mit welchen Tools Azure verwaltet, automatisiert und überwacht wird.', topics:[
        {title:'Azure Portal', learn:'Das Azure Portal ist die grafische Weboberfläche zur Verwaltung von Azure-Ressourcen.', example:'VM erstellen, Kosten ansehen, Ressourcen konfigurieren.', check:'Portal = grafische Verwaltung.'},
        {title:'Cloud Shell, CLI und PowerShell', learn:'Azure Cloud Shell ist eine browserbasierte Shell mit Azure CLI und PowerShell. CLI und PowerShell ermöglichen skriptbare Verwaltung.', example:'Ressourcen per Kommando erstellen oder automatisiert abfragen.', check:'CLI/PowerShell = Automatisierung und Kommandozeile.'},
        {title:'Azure Arc', learn:'Azure Arc erweitert Azure-Verwaltung auf Ressourcen außerhalb von Azure, z. B. lokale Server oder andere Clouds.', example:'On-premises Server über Azure verwalten und Richtlinien anwenden.', check:'Arc = Hybrid-/Multicloud-Verwaltung.'},
        {title:'Infrastructure as Code', learn:'Infrastructure as Code beschreibt Infrastruktur in Dateien/Templates, sodass Deployments reproduzierbar und versionierbar sind.', example:'Statt manuell im Portal zu klicken, wird Infrastruktur per Template bereitgestellt.', check:'IaC = Infrastruktur wie Code behandeln.'},
        {title:'ARM und ARM Templates', learn:'Azure Resource Manager ist die Deployment- und Verwaltungsschicht von Azure. ARM Templates sind JSON-Vorlagen für deklarative Deployments.', example:'Eine Vorlage erstellt Storage Account, App Service und Netzwerk reproduzierbar.', check:'ARM = Verwaltungsschicht; Template = wiederholbare Definition.'},
        {title:'Azure Advisor', learn:'Azure Advisor gibt Empfehlungen zu Kosten, Sicherheit, Zuverlässigkeit, Leistung und operativer Exzellenz.', example:'Advisor empfiehlt, ungenutzte Ressourcen zu löschen oder VM-Größen anzupassen.', check:'Advisor = Empfehlungen.'},
        {title:'Azure Service Health', learn:'Service Health informiert über Azure-Dienstprobleme, geplante Wartungen und Auswirkungen auf deine Ressourcen.', example:'Du prüfst, ob eine Störung in einer Azure Region deine App betrifft.', check:'Service Health = Azure-Status für deine Dienste.'},
        {title:'Azure Monitor, Log Analytics, Alerts, Application Insights', learn:'Azure Monitor sammelt Metriken und Logs. Log Analytics ermöglicht Log-Abfragen. Alerts benachrichtigen bei Bedingungen. Application Insights überwacht Anwendungen und Performance.', example:'Alarm, wenn CPU dauerhaft hoch ist; App Insights zeigt langsame Requests.', check:'Monitor = Beobachtung; Log Analytics = Logs abfragen; App Insights = App-Telemetrie.'}
      ]}
    ]},
    { id:'python', title:'Phase 2: Python + Azure AI Begriffe', subtitle:'Brücke zwischen AZ-900 und AI-901', weeks:'Woche 5–6', modules:[
      {id:'py-syntax', title:'Python Syntax, Daten & Kontrollfluss', time:'AI-901 Vorbereitung', tags:['Python','Syntax','Daten'], summary:'Du lernst genug Python, um SDK-Beispiele, kleine Clients und AI-Workflows zu verstehen.', topics:[
        {title:'Variablen und Datentypen', learn:'Variablen speichern Werte. Wichtige Typen sind Strings, Integers, Floats und Booleans. In AI-Beispielen speicherst du oft Endpoints, Modellnamen, Prompts oder Antworten.', example:'endpoint = "https://..."; temperature = 0.7; is_ready = True', check:'Kannst du erkennen, ob ein Wert Text, Zahl oder Wahr/Falsch ist?'},
        {title:'Listen und Dictionaries', learn:'Listen speichern mehrere Werte in Reihenfolge. Dictionaries speichern Schlüssel-Wert-Paare. JSON-Antworten aus APIs ähneln oft Dictionaries.', example:'messages = [{"role":"user", "content":"Hallo"}]', check:'Liste = mehrere Elemente; Dictionary = Schlüssel und Wert.'},
        {title:'Bedingungen', learn:'Mit if/elif/else entscheidet Code anhand von Bedingungen. Das brauchst du z. B., um API-Status oder Nutzereingaben zu prüfen.', example:'if score >= 700: print("Bestanden")', check:'Kannst du einfache Entscheidungslogik lesen?'},
        {title:'Schleifen', learn:'For-Schleifen gehen durch Listen oder andere Sammlungen. In AI-Apps nutzt man sie z. B. für mehrere Dokumente, Nachrichten oder Ergebnisse.', example:'for file in files: analyze(file)', check:'Schleife = gleiche Aktion für mehrere Elemente.'}
      ]},
      {id:'py-functions-errors', title:'Funktionen, Module, Fehler & Umgebung', time:'AI-901 Vorbereitung', tags:['Functions','Imports','Env'], summary:'Du lernst die Bausteine, aus denen kleine Azure-AI-Clients bestehen.', topics:[
        {title:'Funktionen', learn:'Funktionen kapseln wiederverwendbare Logik. Sie nehmen Eingaben entgegen und geben Ergebnisse zurück.', example:'def summarize(text): return client.complete(text)', check:'Funktion = benannte, wiederverwendbare Aktion.'},
        {title:'Imports und Packages', learn:'Imports laden Module oder SDKs. Azure-Beispiele importieren häufig Clients, Credentials oder Hilfsbibliotheken.', example:'from azure.identity import DefaultAzureCredential', check:'Import = vorhandene Bibliothek nutzen.'},
        {title:'Umgebungsvariablen', learn:'Keys und Endpoints sollten nicht hart im Code stehen. Sie werden häufig über Umgebungsvariablen gelesen.', example:'endpoint = os.environ["AZURE_AI_ENDPOINT"]', check:'Geheimnisse nicht in Code kopieren.'},
        {title:'Fehler lesen', learn:'Ein Traceback zeigt, welche Datei, Zeile und Fehlermeldung betroffen ist. Du musst nicht jeden Fehler perfekt lösen, aber die Richtung erkennen.', example:'KeyError bedeutet oft: gesuchter Dictionary-Key oder Umgebungsvariable fehlt.', check:'Fehlermeldung lesen: Was fehlt? Wo passiert es?'}
      ]},
      {id:'api-rest-json', title:'REST APIs, JSON & Authentifizierung', time:'AI-901 Vorbereitung', tags:['REST','JSON','Auth'], summary:'AI-901 nennt REST APIs, SDKs und CLIs ausdrücklich als vertraute Werkzeuge; hier lernst du die Grundlogik.', topics:[
        {title:'Endpoint', learn:'Ein Endpoint ist die Adresse eines Dienstes. Eine App sendet Anfragen an diese URL.', example:'https://dein-dienst.cognitiveservices.azure.com/', check:'Endpoint = wohin die Anfrage geht.'},
        {title:'Request und Response', learn:'Ein Request ist die Anfrage an einen Dienst; eine Response ist die Antwort. Die Antwort enthält Daten, Statuscodes und ggf. Fehlermeldungen.', example:'Request: „Analysiere diesen Text“. Response: erkannte Stimmung und Schlüsselwörter.', check:'Request rein, Response raus.'},
        {title:'JSON', learn:'JSON ist ein häufiges Datenformat für APIs. Es besteht aus Objekten, Arrays, Strings, Zahlen und Booleans.', example:'{"sentiment":"positive","score":0.93}', check:'JSON ähnelt Python-Dictionaries und Listen.'},
        {title:'API Key, Token und Credentials', learn:'APIs müssen wissen, wer anfragt und ob Zugriff erlaubt ist. Das passiert über API Keys, Tokens oder Azure Credentials.', example:'Eine App sendet einen Authorization-Header oder nutzt DefaultAzureCredential.', check:'Authentifizierung = wer bist du? Autorisierung = was darfst du?'}
      ]},
      {id:'sdk-cli-foundation', title:'SDK, CLI & Azure-Ressourcen-Grundlage', time:'AI-901 Vorbereitung', tags:['SDK','CLI','Resources'], summary:'Du verstehst den typischen Ablauf kleiner Azure-AI-Anwendungen.', topics:[
        {title:'SDK', learn:'Ein SDK ist eine Programmbibliothek, die direkte API-Aufrufe vereinfacht. Statt HTTP manuell zu bauen, nutzt du Client-Objekte und Methoden.', example:'client = SomeAzureAIClient(endpoint, credential)', check:'SDK = komfortabler Weg zur API.'},
        {title:'CLI', learn:'Eine CLI ist ein Kommandozeilenwerkzeug. Mit CLIs kannst du Ressourcen erstellen, konfigurieren, testen und automatisieren.', example:'az login, az group create, az account show', check:'CLI = Verwaltung über Befehle.'},
        {title:'Azure Resource', learn:'Eine Azure Resource ist ein verwaltetes Objekt in Azure, z. B. Storage Account, AI Service, App Service oder Modellbereitstellung.', example:'Für eine AI-App brauchst du oft Resource Group, AI Foundry/AI Service, Deployment und ggf. Storage.', check:'Resource = konkretes Azure-Objekt.'},
        {title:'Typischer AI-Client-Ablauf', learn:'1. Konfiguration laden. 2. Authentifizieren. 3. Client erstellen. 4. Prompt/Daten senden. 5. Antwort auswerten. 6. Fehler behandeln.', example:'Eine Chat-App sendet System- und User-Prompt an ein Deployment und zeigt die Antwort an.', check:'Diesen Ablauf musst du konzeptionell sicher verstehen.'}
      ]}
    ]},
    { id:'ai901', title:'Phase 3: AI-901 bestehen', subtitle:'Microsoft Azure AI Fundamentals', weeks:'Woche 7–10', modules:[
      {id:'ai-responsible', title:'Responsible AI vollständig verstehen', time:'AI-901 · 40–45%', tags:['Fairness','Safety','Privacy'], summary:'Du lernst die sechs Responsible-AI-Prinzipien anhand prüfungsnaher Szenarien.', topics:[
        {title:'Fairness', learn:'Fairness bedeutet, dass AI-Systeme Gruppen nicht unfair benachteiligen. Daten, Modellverhalten und Ergebnisse müssen auf Verzerrungen geprüft werden.', example:'Ein Bewerbungsmodell benachteiligt systematisch eine Altersgruppe.', check:'Szenario mit Diskriminierung/Bias → Fairness.'},
        {title:'Reliability and Safety', learn:'AI-Systeme sollen zuverlässig und sicher funktionieren, besonders bei kritischen Entscheidungen. Grenzen, Tests und Fail-Safes sind wichtig.', example:'Ein medizinischer Chatbot gibt gefährliche Empfehlungen ohne Warnhinweise.', check:'Szenario mit gefährlichem oder unzuverlässigem Verhalten → Reliability/Safety.'},
        {title:'Privacy and Security', learn:'Daten müssen geschützt und nur angemessen verwendet werden. Dazu gehören Zugriffsschutz, Datensparsamkeit, Verschlüsselung und Schutz vor Missbrauch.', example:'Eine App speichert vertrauliche Prompts unnötig lange oder gibt Daten preis.', check:'Szenario mit Daten-/Zugriffsrisiko → Privacy/Security.'},
        {title:'Inclusiveness', learn:'AI-Lösungen sollen für möglichst viele Menschen nutzbar sein, einschließlich Menschen mit Einschränkungen, unterschiedlichen Sprachen oder Nutzungskontexten.', example:'Ein Sprachsystem funktioniert nur mit bestimmten Akzenten zuverlässig.', check:'Szenario mit Barrierefreiheit/Nutzbarkeit für Gruppen → Inclusiveness.'},
        {title:'Transparency', learn:'Nutzer sollen verstehen, dass AI eingesetzt wird, was das System kann, was es nicht kann und wie Ergebnisse zustande kommen können.', example:'Eine Website lässt Nutzer glauben, mit einem Menschen zu sprechen, obwohl es ein Bot ist.', check:'Szenario mit Offenlegung/Erklärbarkeit → Transparency.'},
        {title:'Accountability', learn:'Menschen und Organisationen bleiben verantwortlich für Entwicklung, Einsatz, Überwachung und Folgen von AI-Systemen.', example:'Niemand prüft Beschwerden über fehlerhafte Modellentscheidungen.', check:'Szenario mit fehlender Verantwortung/Review → Accountability.'}
      ]},
      {id:'ai-models-config', title:'Generative AI Modelle, Fähigkeiten & Konfiguration', time:'AI-901 · 40–45%', tags:['Models','Deployments','Parameters'], summary:'Du verstehst, wie generative Modelle konzeptionell funktionieren und wie man Modelloptionen zuordnet.', topics:[
        {title:'Wie generative AI funktioniert', learn:'Generative AI Modelle erzeugen neue Inhalte wie Text, Code, Bilder oder Antworten, indem sie Muster aus Trainingsdaten und Kontext verwenden. Sie liefern wahrscheinliche Ausgaben, keine garantierten Wahrheiten.', example:'Ein Modell beantwortet eine Frage, schreibt eine Zusammenfassung oder erzeugt ein Bild aus einem Prompt.', check:'Generative AI = erzeugt Inhalte; nicht automatisch korrekt.'},
        {title:'Capabilities', learn:'Modelle unterscheiden sich nach Fähigkeiten: Text, Vision, Audio/Speech, Bildgenerierung, Embeddings, multimodal oder agentic Nutzung.', example:'Bild + Frage interpretieren → multimodales Modell; semantische Suche → Embeddings.', check:'Modell nach Aufgabe auswählen.'},
        {title:'Deployment', learn:'Ein Modell muss bereitgestellt werden, damit Anwendungen es aufrufen können. Ein Deployment ist die nutzbare Instanz/Referenz eines Modells in deiner Umgebung.', example:'Eine App ruft nicht abstrakt „ein Modell“ auf, sondern ein konkretes Deployment.', check:'Deployment = App-nutzbare Bereitstellung.'},
        {title:'Configuration Parameters', learn:'Konfigurationsparameter beeinflussen Ausgabe und Verhalten, z. B. Modellwahl, maximale Ausgabe, Temperature oder System Message.', example:'Niedrige Temperature für konsistentere Antworten; höhere für kreativere Varianten.', check:'Parameter steuern Verhalten, sie ersetzen kein gutes Prompting und keine Prüfung.'}
      ]},
      {id:'ai-workloads-core', title:'AI Workloads erkennen', time:'AI-901 · 40–45%', tags:['GenAI','Agents','Workloads'], summary:'Du lernst, welcher AI-Workload zu welchem Problem passt.', topics:[
        {title:'Generative AI', learn:'Generative AI erstellt Inhalte: Texte, Zusammenfassungen, Antworten, Code, Bilder oder multimodale Ergebnisse.', example:'Ein Assistent fasst Kundentickets zusammen.', check:'Inhalt erzeugen → Generative AI.'},
        {title:'Agentic AI', learn:'Agentic AI geht über einzelne Antworten hinaus. Ein Agent kann Aufgaben planen, Tools verwenden, Schritte ausführen und auf Ziele hinarbeiten.', example:'Ein Agent sucht Informationen, ruft ein Tool auf und erstellt anschließend einen Bericht.', check:'Planen + Toolnutzung + Aktionen → Agentic AI.'},
        {title:'Text Analysis', learn:'Text Analysis extrahiert Bedeutung aus Text. Dazu gehören Keywords, Entitäten, Stimmung und Zusammenfassungen.', example:'Kundenfeedback nach Stimmung und Hauptproblemen auswerten.', check:'Text verstehen/klassifizieren/extrahieren → Text Analysis.'},
        {title:'Speech', learn:'Speech umfasst Sprache-zu-Text und Text-zu-Sprache. Es kann für Transkription, Diktat, Sprachassistenten oder Vorlesen genutzt werden.', example:'Eine App transkribiert ein Meeting und liest eine Antwort vor.', check:'Audio/Sprache rein oder raus → Speech.'},
        {title:'Computer Vision', learn:'Computer Vision analysiert Bilder und visuelle Inhalte, z. B. Bildbeschreibung, Objekterkennung oder OCR.', example:'Ein System erkennt Text und Objekte auf einem Foto.', check:'Bild verstehen → Vision.'},
        {title:'Information Extraction', learn:'Information Extraction gewinnt strukturierte Informationen aus Text, Dokumenten, Bildern, Audio oder Video.', example:'Rechnungsnummer, Betrag und Datum aus Rechnungen extrahieren.', check:'Strukturierte Felder aus unstrukturierten Medien → Extraction.'}
      ]},
      {id:'ai-text-speech-vision', title:'Text, Speech, Vision & Image Generation', time:'AI-901 · 40–45%', tags:['NLP','Speech','Vision'], summary:'Du lernst die prüfungsrelevanten Untertechniken der AI-Workloads.', topics:[
        {title:'Keyword Extraction', learn:'Keyword Extraction findet wichtige Begriffe oder Phrasen in Texten.', example:'Aus „Der Versand war schnell, aber die Verpackung beschädigt“ werden Versand, Verpackung, beschädigt.', check:'Wichtige Begriffe finden → Keyword Extraction.'},
        {title:'Entity Detection', learn:'Entity Detection erkennt benannte Entitäten wie Personen, Orte, Organisationen, Daten, Beträge oder Produkte.', example:'„Microsoft eröffnete in Berlin ein Büro“ → Microsoft = Organisation, Berlin = Ort.', check:'Namen/Orte/Organisationen/Werte erkennen → Entity Detection.'},
        {title:'Sentiment Analysis', learn:'Sentiment Analysis erkennt Stimmung oder Meinung in Text: positiv, neutral, negativ oder gemischt.', example:'„Support war nett, aber Produkt kaputt“ → gemischt/negativ.', check:'Stimmung erkennen → Sentiment.'},
        {title:'Summarization', learn:'Summarization fasst längere Inhalte kürzer zusammen, extraktiv oder abstraktiv.', example:'Langes Support-Ticket wird zu drei Kernpunkten.', check:'Kurzfassung erstellen → Summarization.'},
        {title:'Speech Recognition', learn:'Speech Recognition wandelt gesprochene Sprache in Text um.', example:'Mikrofonaufnahme → Transkript.', check:'Sprache zu Text.'},
        {title:'Speech Synthesis', learn:'Speech Synthesis wandelt Text in gesprochene Sprache um.', example:'Antworttext wird dem Nutzer vorgelesen.', check:'Text zu Sprache.'},
        {title:'Computer Vision Features', learn:'Vision-Features können Bilder beschreiben, Objekte erkennen, Text per OCR lesen oder visuelle Inhalte interpretieren.', example:'Foto eines Schildes → Text erkennen und beschreiben.', check:'Bildanalyse/OCR/Objekte → Vision.'},
        {title:'Image Generation', learn:'Image-Generation-Modelle erzeugen neue Bilder oder visuelle Inhalte aus Prompts.', example:'„Erstelle ein Icon für eine Lern-App“ → Bildoutput.', check:'Neues Bild erzeugen → Image Generation.'}
      ]},
      {id:'ai-foundry-basics', title:'Microsoft Foundry: Portal, Prompts & Deployments', time:'AI-901 · 55–60%', tags:['Foundry','Prompts','Portal'], summary:'Du verstehst Foundry als Arbeitsumgebung für Modelle, Apps, Agents und Tools.', topics:[
        {title:'Foundry Portal', learn:'Im Foundry Portal kannst du mit Modellen, Deployments, Prompts, Agents und Tools arbeiten. Für AI-901 musst du die Umgebung konzeptionell und leicht praktisch einordnen können.', example:'Modell auswählen, Deployment erstellen, Prompt testen.', check:'Foundry Portal = zentrale Arbeitsumgebung für AI-Lösungen.'},
        {title:'System Prompts', learn:'System Prompts definieren Rolle, Verhalten, Grenzen und Regeln eines generativen Modells.', example:'„Du bist ein Support-Assistent. Antworte freundlich und kurz. Frage nach, wenn Informationen fehlen.“', check:'System Prompt = Grundverhalten.'},
        {title:'User Prompts', learn:'User Prompts enthalten die konkrete Nutzeranfrage oder Aufgabe.', example:'„Fasse diese E-Mail in drei Stichpunkten zusammen.“', check:'User Prompt = konkrete Aufgabe.'},
        {title:'Effektive Prompts', learn:'Gute Prompts enthalten Ziel, Kontext, Format, Einschränkungen und gewünschte Ausgabe. Schlechte Prompts sind unklar und führen zu unzuverlässigeren Ergebnissen.', example:'Besser: „Gib mir eine Tabelle mit Risiko, Ursache, nächstem Schritt“ statt „Analysiere das mal“.', check:'Gute Prompts machen Aufgabe und Ausgabeformat klar.'},
        {title:'Interaktion mit Deployment', learn:'Nach dem Deployment kannst du ein Modell im Portal testen oder aus einer Anwendung ansprechen.', example:'Prompt im Playground testen, danach denselben Deployment-Namen in der App verwenden.', check:'Portaltest → App-Nutzung.'}
      ]},
      {id:'ai-foundry-sdk-client', title:'Lightweight Chat Client mit Foundry SDK', time:'AI-901 · 55–60%', tags:['SDK','Client','Chat'], summary:'Du lernst die Struktur einer kleinen Chat-Anwendung, ohne direkt Profi-Entwickler sein zu müssen.', topics:[
        {title:'Client-Struktur', learn:'Eine lightweight App lädt Konfiguration, authentifiziert sich, erstellt einen Client, sendet Nachrichten und verarbeitet die Antwort.', example:'Konfig laden → Credential → Client → messages senden → response anzeigen.', check:'Ablauf in Worten erklären können.'},
        {title:'Messages', learn:'Chat-Anfragen bestehen typischerweise aus Rollen und Inhalten, z. B. system, user und assistant.', example:'[{role:"system",content:"..."},{role:"user",content:"..."}]', check:'Chat-Kontext = Nachrichten mit Rollen.'},
        {title:'Fehler- und Antwortverarbeitung', learn:'Eine App sollte Antworten prüfen, Fehler abfangen und Ausgaben nutzbar darstellen.', example:'Wenn Authentifizierung fehlschlägt, bekommt der Nutzer eine klare Fehlermeldung.', check:'Client nicht nur senden lassen, sondern Ergebnis/Fehler behandeln.'},
        {title:'Was AI-901 wahrscheinlich erwartet', learn:'Du sollst keine große Produktions-App bauen, aber eine leichte Client-App mit SDK konzeptionell erstellen und verstehen können.', example:'Welche Schritte braucht eine kleine App, die einen Prompt an ein Foundry-Deployment sendet?', check:'Nicht Framework auswendig lernen, sondern Ablauf verstehen.'}
      ]},
      {id:'ai-agents', title:'Single-Agent-Lösungen verstehen', time:'AI-901 · 55–60%', tags:['Agents','Tools','Testing'], summary:'Du verstehst, was ein Agent ist und wie man ihn im Foundry-Kontext testet und anbindet.', topics:[
        {title:'Agent', learn:'Ein Agent ist eine AI-Lösung, die Aufgaben zielgerichteter bearbeiten kann als ein einzelner Chat-Prompt. Er kann Anweisungen, Kontext und Werkzeuge nutzen.', example:'Ein Agent beantwortet Supportfragen und nutzt ein Wissenssuch-Tool.', check:'Agent = Modell + Anweisungen + ggf. Tools/Aktionen.'},
        {title:'Single-Agent Solution', learn:'Eine Single-Agent-Lösung hat einen Agenten für eine definierte Aufgabe. In AI-901 geht es um Erstellen und Testen im Foundry Portal.', example:'Ein Lerncoach-Agent erklärt AZ-900-Begriffe und stellt Quizfragen.', check:'Ein Agent, klarer Zweck, im Portal testen.'},
        {title:'Agent Client Application', learn:'Eine lightweight Client-App für einen Agent verbindet sich mit dem Agenten, sendet Nutzereingaben und zeigt Antworten oder Aktionen an.', example:'Mobile Web-App sendet Frage an Lernagent und zeigt Antwort.', check:'Agent nutzen = Client spricht Agent an, nicht nur direktes Modell.'},
        {title:'Testen', learn:'Beim Testen prüfst du, ob der Agent richtige Tools nutzt, Regeln einhält, hilfreiche Antworten gibt und Grenzen respektiert.', example:'Testfrage mit absichtlich unklarer Anfrage: Agent soll nachfragen statt halluzinieren.', check:'Agent nicht blind vertrauen, Verhalten prüfen.'}
      ]},
      {id:'ai-foundry-text-speech', title:'Foundry: Text- und Speech-Lösungen', time:'AI-901 · 55–60%', tags:['Text','Speech','Multimodal'], summary:'Du lernst, wie Textanalyse und Sprachfunktionen in leichten Anwendungen eingeordnet werden.', topics:[
        {title:'Text Analysis Application', learn:'Eine App mit Text Analysis nimmt Text entgegen, ruft Analysefunktionen auf und zeigt strukturierte Ergebnisse wie Keywords, Entitäten, Stimmung oder Zusammenfassung.', example:'Supporttickets analysieren und nach negativer Stimmung priorisieren.', check:'Input Text → Analyse → strukturierter Output.'},
        {title:'Spoken Prompts mit multimodalem Modell', learn:'Gesprochene Prompts müssen zunächst erfasst oder transkribiert werden. Ein multimodales Modell kann je nach Fähigkeit Sprache/Audio oder transkribierten Text verarbeiten.', example:'Nutzer spricht eine Frage, App verarbeitet sie und gibt eine AI-Antwort.', check:'Spracheingabe → Modellverarbeitung → Antwort.'},
        {title:'Azure Speech in Foundry Tools', learn:'Azure Speech kann für Speech Recognition und Speech Synthesis in AI-Lösungen eingebunden werden.', example:'Lern-App hört Frage und liest Erklärung vor.', check:'Speech Recognition = rein; Speech Synthesis = raus.'},
        {title:'Praxisverständnis', learn:'Prüfungsnah ist die Frage: Welche Funktion löst welches Szenario und wie sieht die grobe App-Architektur aus?', example:'Meeting-Audio zusammenfassen: Speech-to-text plus Summarization.', check:'Kombiniere Workloads logisch.'}
      ]},
      {id:'ai-foundry-vision-image', title:'Foundry: Vision & Image Generation', time:'AI-901 · 55–60%', tags:['Vision','Images','Multimodal'], summary:'Du verstehst visuelle Eingaben und generierte visuelle Ausgaben im Foundry-Kontext.', topics:[
        {title:'Visual Input in Prompts', learn:'Multimodale Modelle können Bild und Text gemeinsam verarbeiten, z. B. „Was ist auf diesem Bild?“ oder „Extrahiere die relevanten Informationen“.', example:'Foto einer Rechnung plus Prompt: „Nenne Betrag, Datum und Lieferant.“', check:'Bild + Textfrage → multimodales Modell.'},
        {title:'Vision Capabilities', learn:'Vision-Funktionen können Bilder analysieren, beschreiben, Objekte erkennen oder Text erkennen. Eine leichte App sendet Bilddaten und verarbeitet die Antwort.', example:'Produktbild automatisch beschreiben lassen.', check:'Bild verstehen → Vision.'},
        {title:'Visual Output Generation', learn:'Generative Modelle können neue visuelle Outputs erstellen, z. B. Bilder, Designs oder Illustrationen aus Beschreibungen.', example:'Marketing erstellt Varianten eines Produktbanners aus einem Prompt.', check:'Bild erzeugen → generatives Bildmodell.'},
        {title:'Grenzen und Prüfung', learn:'Visuelle Modelle können Fehler machen. Ergebnisse sollten geprüft werden, besonders bei sicherheitsrelevanten oder geschäftskritischen Anwendungen.', example:'OCR liest eine Zahl falsch; App sollte menschliche Prüfung ermöglichen.', check:'AI-Ausgabe validieren.'}
      ]},
      {id:'ai-content-understanding', title:'Content Understanding & Information Extraction', time:'AI-901 · 55–60%', tags:['Extraction','Documents','Audio'], summary:'Du lernst, wie Informationen aus Dokumenten, Formularen, Bildern, Audio und Video extrahiert werden.', topics:[
        {title:'Dokumente und Formulare', learn:'Content Understanding kann strukturierte Informationen aus Dokumenten und Formularen extrahieren, z. B. Felder, Werte, Tabellen oder Schlüsselangaben.', example:'Rechnung → Rechnungsnummer, Lieferant, Betrag, Datum.', check:'Dokument/Formular → strukturierte Daten.'},
        {title:'Bilder', learn:'Aus Bildern können sichtbare Informationen extrahiert werden, z. B. Text, Objekte oder relevante visuelle Merkmale.', example:'Foto eines Ausweises oder Formulars → erkannte Felder und Text.', check:'Bildinhalt → Daten.'},
        {title:'Audio und Video', learn:'Aus Audio und Video können Informationen aus Sprache, visuellen Szenen oder zeitbasierten Inhalten gewonnen werden.', example:'Schulungsvideo → Themen, Aussagen, relevante Zeitpunkte.', check:'Audio/Video → nutzbare Informationen.'},
        {title:'Lightweight Extraction Application', learn:'Eine leichte App lädt Datei oder Medium hoch, sendet es an Content Understanding, erhält strukturierte Ergebnisse und zeigt sie an oder speichert sie.', example:'Mobile App fotografiert Beleg und übernimmt Betrag in eine Tabelle.', check:'Upload → Analyse → strukturierte Felder → Weiterverarbeitung.'},
        {title:'Wann Content Understanding statt einfachem Chat?', learn:'Wenn du aus Dokumenten, Formularen oder Medien verlässlich strukturierte Informationen extrahieren willst, ist ein spezialisierter Extraction-Ansatz passender als nur freier Chat.', example:'„Ziehe Betrag, IBAN und Rechnungsdatum in JSON“ ist Extraction, nicht nur Zusammenfassung.', check:'Strukturierte Felder aus Medien → Content Understanding.'}
      ]}
    ]}
  ],
  quiz: [
    {q:'Welche Reihenfolge beschreibt die Azure-Hierarchie korrekt?', a:['Management Group → Subscription → Resource Group → Resource','Resource Group → Management Group → Subscription → Resource','Subscription → Resource → Management Group → Resource Group'], c:0, why:'Management Groups organisieren Subscriptions; darunter liegen Resource Groups und darin Resources.'},
    {q:'Bei welchem Servicemodell hat der Kunde typischerweise die meiste Verantwortung?', a:['SaaS','PaaS','IaaS'], c:2, why:'Bei IaaS verwaltet der Kunde mehr, z. B. Betriebssystem, Patches und Konfiguration.'},
    {q:'Was bedeutet Serverless im Azure-Kontext?', a:['Es gibt keine Server','Du verwaltest die Server nicht selbst','Es funktioniert nur ohne Internet'], c:1, why:'Server existieren weiterhin, aber der Anbieter abstrahiert die Serververwaltung.'},
    {q:'Welche Option passt zu einer privaten Verbindung zu Azure ohne öffentliches Internet?', a:['ExpressRoute','Public Endpoint','Azure DNS'], c:0, why:'ExpressRoute bietet eine private Verbindung zu Azure.'},
    {q:'Wofür nutzt man Azure Policy?', a:['Ressourcen-Regeln erzwingen oder Compliance prüfen','Text in Sprache umwandeln','VMs automatisch patchen'], c:0, why:'Azure Policy definiert und überwacht Regeln für Ressourcen.'},
    {q:'Welches Tool schätzt Kosten vor der Bereitstellung?', a:['Azure Pricing Calculator','Azure Service Health','Application Insights'], c:0, why:'Der Pricing Calculator hilft bei der Vorabschätzung von Kosten.'},
    {q:'Was ist RBAC?', a:['Rollenbasierte Zugriffskontrolle','Regionale Backup-Kopie','Abrechnung pro Ressource'], c:0, why:'RBAC steuert, wer welche Aktionen auf welchem Scope ausführen darf.'},
    {q:'Welche Aussage passt zu Zero Trust?', a:['Interne Nutzer sind automatisch vertrauenswürdig','Immer explizit prüfen und minimale Rechte vergeben','Nur Firewalls reichen aus'], c:1, why:'Zero Trust basiert auf expliziter Prüfung, Least Privilege und Annahme möglicher Kompromittierung.'},
    {q:'Welcher Storage-Typ eignet sich für unstrukturierte Dateien wie Bilder und PDFs?', a:['Blob Storage','Queue Storage','Azure Policy'], c:0, why:'Blob Storage ist Objektspeicher für unstrukturierte Daten.'},
    {q:'Was macht Queue Storage?', a:['Nachrichten zwischenspeichern und Systeme entkoppeln','Virtuelle Desktops bereitstellen','DNS-Zonen hosten'], c:0, why:'Queues dienen der asynchronen Kommunikation zwischen Komponenten.'},
    {q:'Wofür ist Azure Service Health gedacht?', a:['Code schreiben','Azure-Dienstprobleme und Wartungen anzeigen','Bilder generieren'], c:1, why:'Service Health informiert über Azure-Probleme und geplante Wartungen.'},
    {q:'Was macht Application Insights?', a:['App-Telemetrie und Performance überwachen','Ressourcen löschen verhindern','Private Netzwerke verbinden'], c:0, why:'Application Insights ist auf Anwendungsüberwachung und Telemetrie ausgerichtet.'},
    {q:'Was ist ein API Endpoint?', a:['Die Adresse eines Dienstes','Eine Azure Region','Ein Benutzerkonto'], c:0, why:'Ein Endpoint ist die URL/Adresse, an die eine App Anfragen sendet.'},
    {q:'Was beschreibt JSON am besten?', a:['Ein Datenformat für strukturierte API-Daten','Ein Azure-Rechenzentrum','Ein Passwortverfahren'], c:0, why:'JSON wird häufig für Request- und Response-Daten verwendet.'},
    {q:'Welche Reihenfolge passt zu einem einfachen SDK-Client?', a:['Konfig laden → authentifizieren → Client erstellen → Anfrage senden → Antwort verarbeiten','Antwort verarbeiten → Client löschen → Region wählen','DNS erstellen → Bild generieren → VM patchen'], c:0, why:'Das ist der typische Ablauf kleiner API/SDK-Anwendungen.'},
    {q:'Welches Responsible-AI-Prinzip passt zu Bias gegen bestimmte Gruppen?', a:['Fairness','Transparency','Accountability'], c:0, why:'Fairness betrifft gerechte Behandlung und Vermeidung unfairer Benachteiligung.'},
    {q:'Welches Prinzip passt zu Offenlegung, dass ein Nutzer mit AI spricht?', a:['Transparency','Inclusiveness','Scalability'], c:0, why:'Transparency betrifft Offenlegung, Erklärbarkeit und Kommunikation von Grenzen.'},
    {q:'Was ist Generative AI?', a:['AI, die neue Inhalte erzeugt','Ein privates Netzwerk','Eine Kostenwarnung'], c:0, why:'Generative AI erzeugt Text, Bilder, Code oder andere Inhalte.'},
    {q:'Was ist Agentic AI?', a:['Ein Modell, das nur Bilder speichert','Eine AI-Lösung, die Ziele verfolgt und Tools nutzen kann','Ein Storage-Tier'], c:1, why:'Agentic AI plant Aufgaben und kann Werkzeuge/Aktionen verwenden.'},
    {q:'Was macht Sentiment Analysis?', a:['Stimmung in Text erkennen','Text zu Sprache umwandeln','Netzwerke verbinden'], c:0, why:'Sentiment Analysis erkennt z. B. positive, neutrale oder negative Stimmung.'},
    {q:'Was ist Speech Recognition?', a:['Text wird vorgelesen','Sprache wird in Text umgewandelt','Bilder werden analysiert'], c:1, why:'Speech Recognition = Sprache zu Text.'},
    {q:'Was ist Speech Synthesis?', a:['Text wird in Sprache umgewandelt','Sprache wird gelöscht','Netzwerk wird verschlüsselt'], c:0, why:'Speech Synthesis = Text zu Sprache.'},
    {q:'Welche Aufgabe passt zu Computer Vision?', a:['Objekte in einem Bild erkennen','Kostenbudget setzen','Subscription erstellen'], c:0, why:'Computer Vision analysiert visuelle Inhalte.'},
    {q:'Welche Aufgabe passt zu Information Extraction?', a:['Betrag und Datum aus Rechnung auslesen','VM-Größe erhöhen','Region Pair auswählen'], c:0, why:'Information Extraction gewinnt strukturierte Informationen aus Dokumenten oder Medien.'},
    {q:'Was ist ein System Prompt?', a:['Die konkrete Frage des Nutzers','Grundregeln und Verhalten für das Modell','Ein Azure Storage Account'], c:1, why:'System Prompts definieren Rolle, Stil, Grenzen und Regeln.'},
    {q:'Was ist ein User Prompt?', a:['Die konkrete Aufgabe oder Anfrage des Nutzers','Ein Preisrechner','Eine Resource Group'], c:0, why:'User Prompts enthalten die konkrete Nutzeranfrage.'},
    {q:'Was bedeutet ein Model Deployment?', a:['Die nutzbare Bereitstellung eines Modells für Apps','Ein lokaler Ordner auf dem iPhone','Ein VPN-Tunnel'], c:0, why:'Apps sprechen ein konkretes Deployment an.'},
    {q:'Wann ist ein multimodales Modell passend?', a:['Wenn Text und Bild gemeinsam verarbeitet werden sollen','Nur für Kostenmanagement','Nur für DNS'], c:0, why:'Multimodale Modelle verarbeiten mehrere Modalitäten wie Text und Bild.'},
    {q:'Wofür nutzt man Azure Content Understanding?', a:['Informationen aus Dokumenten, Bildern, Audio oder Video extrahieren','Ressourcen abrechnen','Benutzer per MFA anmelden'], c:0, why:'Content Understanding ist für Information Extraction aus verschiedenen Medientypen relevant.'},
    {q:'Was ist der wichtigste Unterschied zwischen Foundation-Wissen und Prüfungsraten?', a:['Du kannst Szenarien begründen statt nur Antworten auswendig lernen','Du brauchst keine Begriffe','Du musst nur Buttons finden'], c:0, why:'Ziel ist Verständnis: Begriff, Zweck, Use Case und Abgrenzung.'}
  ],
  sources: [
    ['AZ-900 Study Guide','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-900'],
    ['AZ-900 Zertifizierungsseite','https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/'],
    ['AI-901 Study Guide','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ai-901'],
    ['AI-901 Exam Page','https://learn.microsoft.com/en-us/credentials/certifications/exams/ai-901/'],
    ['AI concepts learning path','https://learn.microsoft.com/en-us/training/paths/ai-concepts/']
  ]
};
const LS='azureAiLernapp_v2';
const state=JSON.parse(localStorage.getItem(LS)||'{}');
state.done=state.done||{};state.quiz=state.quiz||{right:0,total:0};state.days=state.days||{};
const today=new Date().toISOString().slice(0,10);state.days[today]=true;save();
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function save(){localStorage.setItem(LS,JSON.stringify(state));}
function allModules(){return DATA.phases.flatMap(p=>p.modules.map(m=>({...m,phase:p.title,phaseSubtitle:p.subtitle})));}
function esc(s){return String(s).replace(/[&<>"']/g, m=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[m]));}
function topicSearchText(m){return m.topics.map(t=>[t.title,t.learn,t.example,t.check].join(' ')).join(' ')}
function updateStats(){const total=allModules().length;const done=Object.keys(state.done).filter(k=>state.done[k]).length;const pct=Math.round(done/total*100)||0;$('#doneCount').textContent=`${done}/${total}`;$('#overallProgress').textContent=pct+'%';document.querySelector('.progress-ring').style.background=`conic-gradient(var(--brand) ${pct*3.6}deg,#dbeafe 0deg)`;const q=state.quiz.total?Math.round(state.quiz.right/state.quiz.total*100):0;$('#quizScore').textContent=q+'%';$('#streak').textContent=Object.keys(state.days).length;}
function renderLearn(filter=''){ $('#detail').classList.add('hidden'); $('#quiz').classList.add('hidden'); const root=$('#path'); root.innerHTML=''; const term=filter.toLowerCase(); DATA.phases.forEach(p=>{const mods=p.modules.filter(m=>!term || (m.title+m.summary+m.tags.join(' ')+topicSearchText(m)).toLowerCase().includes(term)); if(!mods.length)return; const sec=document.createElement('section');sec.className='phase';sec.innerHTML=`<div class="phase-title"><div><h3>${esc(p.title)}</h3><span>${esc(p.subtitle)} · ${esc(p.weeks)}</span></div></div>`; mods.forEach((m,i)=>{const card=document.createElement('article');card.className='module card';card.innerHTML=`<div class="badge">${i+1}</div><div><h3>${esc(m.title)}</h3><p>${esc(m.summary)}</p><div class="pillrow"><span class="pill">${esc(m.time)}</span>${m.tags.map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div></div><button class="check ${state.done[m.id]?'done':''}" aria-label="Modul erledigt">✓</button>`; card.querySelector('.check').onclick=e=>{e.stopPropagation();state.done[m.id]=!state.done[m.id];save();updateStats();renderLearn($('#searchInput').value)}; card.onclick=()=>renderDetail({...m,phase:p.title}); sec.appendChild(card);}); root.appendChild(sec);}); updateStats();}
function renderDetail(m){$('#path').innerHTML=''; const d=$('#detail'); d.classList.remove('hidden'); d.innerHTML=`<button class="back">← Zurück</button><p class="eyebrow">${esc(m.phase||'Lernmodul')}</p><h2>${esc(m.title)}</h2><p>${esc(m.summary)}</p><div class="callout"><strong>Prüfungsfokus:</strong> ${esc(m.time)}. Lerne jeden Punkt als: Begriff → Zweck → Beispiel → Abgrenzung.</div>${m.topics.map(t=>`<div class="topic"><h3>${esc(t.title)}</h3><p>${esc(t.learn)}</p><div class="mini"><strong>Beispiel:</strong> ${esc(t.example)}</div><div class="mini checknote"><strong>Prüfungscheck:</strong> ${esc(t.check)}</div></div>`).join('')}<div class="actions"><button class="primary" id="markDone">Als erledigt markieren</button><button class="secondary" id="flashBtn">Lernkarten</button></div>`; d.querySelector('.back').onclick=()=>renderLearn($('#searchInput').value); d.querySelector('#markDone').onclick=()=>{state.done[m.id]=true;save();updateStats();renderLearn($('#searchInput').value)}; d.querySelector('#flashBtn').onclick=()=>renderFlash(m);}
function renderFlash(m){const facts=m.topics.map(t=>({front:t.title,back:`${t.learn}\n\nBeispiel: ${t.example}\n\nCheck: ${t.check}`}));let idx=0,showBack=false;const d=$('#detail');function draw(){const f=facts[idx];d.innerHTML=`<button class="back">← Modul</button><p class="eyebrow">Lernkarte ${idx+1}/${facts.length}</p><div class="flashcard">${esc(showBack?f.back:f.front).replace(/\n/g,'<br>')}</div><div class="actions"><button class="primary" id="flip">Umdrehen</button><button class="secondary" id="next">Nächste</button></div>`;d.querySelector('.back').onclick=()=>renderDetail(m);d.querySelector('#flip').onclick=()=>{showBack=!showBack;draw()};d.querySelector('#next').onclick=()=>{idx=(idx+1)%facts.length;showBack=false;draw()};}draw();}
let qIndex=0;function renderQuiz(){ $('#path').innerHTML=''; $('#detail').classList.add('hidden'); const q=DATA.quiz[qIndex%DATA.quiz.length]; const root=$('#quiz'); root.classList.remove('hidden'); root.innerHTML=`<p class="eyebrow">Quiz ${qIndex%DATA.quiz.length+1}/${DATA.quiz.length}</p><h2>${esc(q.q)}</h2><div>${q.a.map((x,i)=>`<button class="answer" data-i="${i}">${esc(x)}</button>`).join('')}</div><p id="explain" class="callout hidden"></p><div class="actions"><button class="secondary" id="nextQ">Nächste Frage</button></div>`; $$('.answer').forEach(btn=>btn.onclick=()=>{const chosen=+btn.dataset.i; const ok=chosen===q.c; state.quiz.total++; if(ok)state.quiz.right++; save(); updateStats(); $$('.answer').forEach(b=>{b.disabled=true; if(+b.dataset.i===q.c)b.classList.add('correct');}); if(!ok)btn.classList.add('wrong'); $('#explain').textContent=q.why; $('#explain').classList.remove('hidden');}); $('#nextQ').onclick=()=>{qIndex++;renderQuiz();}; updateStats();}
function renderCheck(){ $('#detail').classList.add('hidden'); $('#quiz').classList.add('hidden'); const root=$('#path'); root.innerHTML='<section class="phase"><div class="phase-title"><h3>Master-Checkliste</h3><span>Tippe ab, was sitzt.</span></div></section>'; allModules().forEach(m=>{const card=document.createElement('article');card.className='module card';card.innerHTML=`<div class="badge">✓</div><div><h3>${esc(m.title)}</h3><p>${esc(m.tags.join(' · '))}</p></div><button class="check ${state.done[m.id]?'done':''}">✓</button>`;card.querySelector('.check').onclick=()=>{state.done[m.id]=!state.done[m.id];save();renderCheck();updateStats();};root.appendChild(card);}); updateStats();}
function renderSources(){ $('#detail').classList.add('hidden'); $('#quiz').classList.add('hidden'); $('#path').innerHTML=`<section class="card detail"><p class="eyebrow">Offizielle Quellen</p><h2>Microsoft Learn</h2><p>Diese App ist eine Lernhilfe entlang der offiziellen Skills-Outlines. Für finale Prüfungsdetails immer die offiziellen Microsoft-Seiten prüfen.</p><div class="source-list">${DATA.sources.map(s=>`<a href="${s[1]}" target="_blank" rel="noopener">${esc(s[0])} ↗</a>`).join('')}</div></section>`;}
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const v=t.dataset.view;if(v==='learn')renderLearn($('#searchInput').value);if(v==='quiz')renderQuiz();if(v==='check')renderCheck();if(v==='sources')renderSources();});
$('#searchInput').addEventListener('input',e=>renderLearn(e.target.value));
$('#themeBtn').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'':'dark'};
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});} renderLearn();
